Markups

diff --git a/clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/check_restart_queue_state b/clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/check_restart_queue_state
--- a/clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/check_restart_queue_state
+++ b/clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/check_restart_queue_state
@@ -18,8 +18,9 @@ then
   exit 1
 fi
 
-# Return 2 if any error occurs. Else return 1 if any node is queueing, and 0 if
-# restart completed.
+# Return code indicates queue state: 2 if any error occurs, 1 if no error occurs
+# and some nodes are still queueing, and 0 if all nodes have restarted
+# successfully.
 if [[ $use_single_restart_queue == "Y" ]] ; then
   /usr/share/clearwater/clearwater-queue-manager/env/bin/python /usr/share/clearwater/clearwater-queue-manager/scripts/check_queue_state.py "${management_local_ip:-$local_ip}" "$local_site_name" apply_config
 else
@@ -30,7 +31,12 @@ else
     apply_config_key=${apply_config_key#$prefix}
 
     /usr/share/clearwater/clearwater-queue-manager/env/bin/python /usr/share/clearwater/clearwater-queue-manager/scripts/check_queue_state.py "${management_local_ip:-$local_ip}" "$local_site_name" "$apply_config_key"
-    rc=$(($?>rc?$?:rc))
+
+    queue_state=$?
+    if [[ $queue_state > $rc ]]
+    then
+        rc=$queue_state  # Higher return code takes precedence
+    fi
   done
   exit $rc
 fi
